name: sensuishi_app
description: A new Flutter project for learning Diver qualification.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  fl_chart: ^0.66.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  supabase_flutter: ^2.8.1
  google_mobile_ads: ^7.0.0
  sqflite: ^2.3.3+3
  path: ^1.9.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  assets:
    - assets/questions/
    - assets/questions/images/
    - assets/fonts/

#  fonts:
#    - family: NotoSansJP
#      fonts:
#        - asset: assets/fonts/NotoSansJP-Regular.ttf
#        - asset: assets/fonts/NotoSansJP-Bold.ttf
#          weight: 700
